@startuml
skin rose

class Propulsion <<(T, Orange)>>
class Terrain{
    +defensiveRating: int {[0,5]}
    +MoveCostOf(:Propulsion): int
}
class Battalion{
    +forces: int
}
class Unit <<(T, Orange)>>
class MovementRate <<(T, Orange)>>
class Nation <<(T, Orange)>>
class Map
class Space
class Coord <<(T, orange)>>
package Fire{
class Offensive{
+Damage: int
}
}

Unit --> Propulsion
Unit --> MovementRate
Map +-- Space
(Map, Space) .. Coord
Space --> Terrain
Terrain --> Propulsion : costs
Battalion --> Nation
Space o-- Battalion : 0..1
Battalion --> Unit
Building -u-|> Terrain

Offensive o--- "2" Battalion : attacker\ndefender
Offensive o--- Terrain : battlefield

@enduml