@startuml
skin rose
autonumber
autoactivate on
boundary CursorView #technology
boundary Input #technology
control CursorMovement #implementation
entity Game
entity Cursor


activate Input
Input -> CursorMovement : Towards(direction)
deactivate Input
CursorMovement -> Game : MoveCursorTowards(direction)
deactivate CursorMovement
Game -> Cursor : WhereIs = direction
return
autoactivate off
Game -> Game : position = Cursor.WhereIs
Game -> CursorMovement : <<event>>\nCursorMoved(position)
activate CursorMovement
deactivate Game

CursorMovement -> CursorView : MoveTo(position)
activate CursorView
deactivate CursorMovement
CursorView -> CursorView : ShowIn(position)
@enduml