@startuml
allowmixing
skin rose

control Control

Game - "2..*" Player
(Player, Game) - Nation

Game --> Operation
Game --> Cursor
Game --> Map

Control --> Game

Operation *-- "1 per player" CO
CO --> Nation
@enduml
